<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RoomsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rooms')->delete();
        
        \DB::table('rooms')->insert(array (
            0 => 
            array (
                'id' => 1,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 1,
                'room_number' => '101',
                'name' => 'Oda 101',
                'description' => '1. kattaki 101 numaralı oda',
                'is_active' => 1,
                'sort_order' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            1 => 
            array (
                'id' => 2,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 1,
                'room_number' => '102',
                'name' => 'Oda 102',
                'description' => '1. kattaki 102 numaralı oda',
                'is_active' => 1,
                'sort_order' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            2 => 
            array (
                'id' => 3,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 1,
                'room_number' => '103',
                'name' => 'Oda 103',
                'description' => '1. kattaki 103 numaralı oda',
                'is_active' => 1,
                'sort_order' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            3 => 
            array (
                'id' => 4,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 1,
                'room_number' => '104',
                'name' => 'Oda 104',
                'description' => '1. kattaki 104 numaralı oda',
                'is_active' => 1,
                'sort_order' => 4,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            4 => 
            array (
                'id' => 5,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 1,
                'room_number' => '105',
                'name' => 'Oda 105',
                'description' => '1. kattaki 105 numaralı oda',
                'is_active' => 1,
                'sort_order' => 5,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            5 => 
            array (
                'id' => 6,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 2,
                'room_number' => '201',
                'name' => 'Oda 201',
                'description' => '2. kattaki 201 numaralı oda',
                'is_active' => 1,
                'sort_order' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            6 => 
            array (
                'id' => 7,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 2,
                'room_number' => '202',
                'name' => 'Oda 202',
                'description' => '2. kattaki 202 numaralı oda',
                'is_active' => 1,
                'sort_order' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            7 => 
            array (
                'id' => 8,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 2,
                'room_number' => '203',
                'name' => 'Oda 203',
                'description' => '2. kattaki 203 numaralı oda',
                'is_active' => 1,
                'sort_order' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            8 => 
            array (
                'id' => 9,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 2,
                'room_number' => '204',
                'name' => 'Oda 204',
                'description' => '2. kattaki 204 numaralı oda',
                'is_active' => 1,
                'sort_order' => 4,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            9 => 
            array (
                'id' => 10,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 2,
                'room_number' => '205',
                'name' => 'Oda 205',
                'description' => '2. kattaki 205 numaralı oda',
                'is_active' => 1,
                'sort_order' => 5,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            10 => 
            array (
                'id' => 11,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 3,
                'room_number' => '301',
                'name' => 'Oda 301',
                'description' => '3. kattaki 301 numaralı oda',
                'is_active' => 1,
                'sort_order' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            11 => 
            array (
                'id' => 12,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 3,
                'room_number' => '302',
                'name' => 'Oda 302',
                'description' => '3. kattaki 302 numaralı oda',
                'is_active' => 1,
                'sort_order' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            12 => 
            array (
                'id' => 13,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 3,
                'room_number' => '303',
                'name' => 'Oda 303',
                'description' => '3. kattaki 303 numaralı oda',
                'is_active' => 1,
                'sort_order' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            13 => 
            array (
                'id' => 14,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 3,
                'room_number' => '304',
                'name' => 'Oda 304',
                'description' => '3. kattaki 304 numaralı oda',
                'is_active' => 1,
                'sort_order' => 4,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            14 => 
            array (
                'id' => 15,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 3,
                'room_number' => '305',
                'name' => 'Oda 305',
                'description' => '3. kattaki 305 numaralı oda',
                'is_active' => 1,
                'sort_order' => 5,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            15 => 
            array (
                'id' => 16,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 4,
                'room_number' => '401',
                'name' => 'Oda 401',
                'description' => '4. kattaki 401 numaralı oda',
                'is_active' => 1,
                'sort_order' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            16 => 
            array (
                'id' => 17,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 4,
                'room_number' => '402',
                'name' => 'Oda 402',
                'description' => '4. kattaki 402 numaralı oda',
                'is_active' => 1,
                'sort_order' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            17 => 
            array (
                'id' => 18,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 4,
                'room_number' => '403',
                'name' => 'Oda 403',
                'description' => '4. kattaki 403 numaralı oda',
                'is_active' => 1,
                'sort_order' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            18 => 
            array (
                'id' => 19,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 4,
                'room_number' => '404',
                'name' => 'Oda 404',
                'description' => '4. kattaki 404 numaralı oda',
                'is_active' => 1,
                'sort_order' => 4,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            19 => 
            array (
                'id' => 20,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 4,
                'room_number' => '405',
                'name' => 'Oda 405',
                'description' => '4. kattaki 405 numaralı oda',
                'is_active' => 1,
                'sort_order' => 5,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            20 => 
            array (
                'id' => 21,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 5,
                'room_number' => '501',
                'name' => 'Oda 501',
                'description' => '5. kattaki 501 numaralı oda',
                'is_active' => 1,
                'sort_order' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            21 => 
            array (
                'id' => 22,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 5,
                'room_number' => '502',
                'name' => 'Oda 502',
                'description' => '5. kattaki 502 numaralı oda',
                'is_active' => 1,
                'sort_order' => 2,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            22 => 
            array (
                'id' => 23,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 5,
                'room_number' => '503',
                'name' => 'Oda 503',
                'description' => '5. kattaki 503 numaralı oda',
                'is_active' => 1,
                'sort_order' => 3,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            23 => 
            array (
                'id' => 24,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 5,
                'room_number' => '504',
                'name' => 'Oda 504',
                'description' => '5. kattaki 504 numaralı oda',
                'is_active' => 1,
                'sort_order' => 4,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
            24 => 
            array (
                'id' => 25,
                'company_id' => 1,
                'user_id' => NULL,
                'floor_id' => 5,
                'room_number' => '505',
                'name' => 'Oda 505',
                'description' => '5. kattaki 505 numaralı oda',
                'is_active' => 1,
                'sort_order' => 5,
                'deleted_at' => NULL,
                'created_at' => '2025-12-21 15:52:54',
                'updated_at' => '2025-12-21 15:52:54',
            ),
        ));
        
        
    }
}